# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackBelt_app', '0002_auto_20171221_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritetrip',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotraveler', to='blackBelt_app.User'),
        ),
        migrations.AlterField(
            model_name='favoritetrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='blackBelt_app.Trip'),
        ),
    ]
